using System.ComponentModel.DataAnnotations;

namespace Contact_Manger.Models
{
    /// <summary>
    /// Category model - represents categories for organizing contacts
    /// 
    /// VARIABLE REFERENCE FOR TEAMMATES:
    /// - CategoryId: int (Primary key, auto-generated by database)
    /// - Name: string (Category name - "Family", "Friend", "Work", etc.)
    /// - Contacts: ICollection<Contact> (Navigation property - all contacts in this category)
    /// </summary>
    public class Category
    {
        // Primary Key - EF Core auto-recognizes this as PK because it's named CategoryId
        // Database will auto-generate values (identity column)
        public int CategoryId { get; set; }

        // Category Name - Required field
        [Required(ErrorMessage = "Please enter a category name.")]
        [StringLength(50)]
        public string Name { get; set; } = string.Empty;

        // Navigation Property - Collection of contacts in this category
        // Enables you to access: category.Contacts to get all related contacts
        public ICollection<Contact>? Contacts { get; set; }
    }
}